name: Conformance Tests

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [labeled]
  workflow_dispatch:

jobs:
  conformance:
    strategy:
      matrix:
        java-version: [11, 17]
      fail-fast: false

    permissions:
      # Needed to access the workflow's OIDC identity.
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Build sigstore-java
        uses: gradle/gradle-build-action@6095a76664413da4c8c134ee32e8a8ae900f0f1f # v2.4.0
        with:
          arguments: :sigstore-cli:build

      - name: Unpack sigstore-java distribution
        run: tar -xvf ${{ github.workspace }}/sigstore-cli/build/distributions/sigstore-cli-*.tar --strip-components 1

      - uses: trailofbits/sigstore-conformance@0748d63c53810e36cc3f4bbe4114301080f0d844 # tag=v0.0.3
        with:
          entrypoint: ${{ github.workspace }}/bin/sigstore-cli
